Itération 3 : Animations des balles
lilmaax/camlbrick pull request #17
Opened 2024-04-08 10:13 UTC by lilmaax

Fonctionne correctement avec une balle.
Bug avec plusieurs balles.

2024-04-08 10:17 UTC, lilmaax commented on camlbrick.ml
> +  done
TODO : ajouter des commentaires

2024-04-09 14:43 UTC, Slepsni requested changes

2024-04-09 14:43 UTC, Slepsni commented on camlbrick.ml
> +  Cette fonction est utilisée par l'interface graphique pour connaitre l'information à afficher dans la zone Custom2 de la zone du menu.
```suggestion
  Cette fonction est utilisée par l'interface graphique pour connaitre l'information à afficher dans la zone Custom1 de la zone du menu.
```

2024-04-09 14:44 UTC, Slepsni approved these changes
lgtm

2024-04-09 14:45 UTC, merged